# OSCAR Configuration Settings
# This file defines the 'Source of Truth' for Default and Standard runs.


paths:
  zenodo_base_url: "https://zenodo.org/records/18290789/files/18290789.zip"


# STANDARD MODE RUN SETTINGS
bootstrap_specs:
  region: "RCP_5reg"
  nMC: 50
  hist_start_year: 1750
  hist_end_year: 2014
  scen_start_year: 2015
  scen_end_year: 2100
  var_full : ['D_Xhalo_lag', 'D_Cfroz', 'D_Tg', 'D_Td', 'D_Csoil1_bk', 'D_N2O_lag', 'D_Csoil2_bk', 'D_OHC', 'D_Xhalo', 'D_CH4', 'D_N2O', 'D_CO2', 'D_cveg', 'D_Chwp', 'D_CH4_lag', 'D_Aland', 'D_csoil2', 'D_Cveg_bk', 'D_pthaw', 'D_Cthaw', 'D_csoil1', 'D_Cosurf', 'D_Pg']
  var_select : ['D_Tg', 'D_CO2', 'D_CH4', 'D_N2O']

#TODO: to populate this part
# Configured MODE RUN Templates (Defaults that can be overridden)
configured_runs:
  historical:
    start_year: 1750
    end_year: 2014
    n_mc: 500
  ssp_projection:
    region: "AR6_10reg"
    n_mc: 200